### ISSUE TITLE
Support settting Nginx variable as property

### ISSUE THREAD

**Issue by spacewander** [api7/wasm-nginx-module#50]

**Comment by bzp2010** [comment]
Hi, @spacewander.

I would like take this work.

**Comment by bzp2010** [comment]
I have a questions, should we only allow the user to set the currently existing ngx_http built-in variables here? If it is allowed to set arbitrary variables (including new ones), it should be possible to use it in a log-like phase, is that right? Would this cause instability or security issues?

**Comment by bzp2010** [comment]
Link #78
